[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_project = "6B8tT1EzLMKUZ5fF5H8cTs4We1vLabVeZtgCnB4Ccmnq"

[programs.localnet]
my_project = "4VgPkuQSgqvaBaE7X5ZyUFeMPRMj7yAa8cgsi22ZTvik"

[programs.mainnet]
my_project = "6B8tT1EzLMKUZ5fF5H8cTs4We1vLabVeZtgCnB4Ccmnq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "bunx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
