// @ts-nocheck — TODO(step5c): rewrite for OLD_Erebor's execute_action.
// Currently calls executeStrategyAction (deleted) with a single-blob ix_data
// and uses the old findAllowedActionByDiscriminator scan helper. Step 5c
// switches to executeAction(strategy_id, target_program, disc, body) with
// the strategy_authority PDA signer + caller_token_ata / delegate_token_ata
// anti-theft snapshots, and uses the new deterministic AllowedAction PDA seeds.
//
// strategy.ts — Lending protocol integration via execute_strategy_action.
//
// This module implements the LuloProtocol interface by calling the vault's
// execute_strategy_action instruction. The agent NEVER calls the lending protocol
// directly — all token movement goes through the vault program's CPI routing.
//
// The same code path works for both devnet (mock_lulo program) and mainnet (real Lulo).
// The only difference is the target program ID and its account layout, which are
// configured via environment variables (LULO_PROGRAM_ID, LULO_TREASURY).
//
// Flow:
//   Agent signs tx → vault validates whitelist → vault CPIs to protocol → tokens move
//
// The agent needs:
//   1. The target protocol's program ID (mock_lulo on devnet, Lulo on mainnet)
//   2. The 8-byte Anchor discriminators for deposit/withdraw instructions
//   3. The protocol's treasury account PDA (where deposited tokens go)

import { Program } from "@coral-xyz/anchor";
import { PublicKey, Connection } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";
import BN from "bn.js";
import type { MyProject } from "../../../target/types/my_project.js";
import type { AgentConfig, AgentDecision, LuloProtocol } from "../../shared/types.js";
import {
  findAllowedActionByDiscriminator,
  fetchTokenBalance,
  deriveProtocolPositionPda,
  fetchProtocolPosition,
} from "../../shared/vault-client.js";

// Anchor discriminators are the first 8 bytes of sha256("global:<instruction_name>").
// These are auto-generated by the Anchor framework and match what's stored
// in AllowedAction PDAs on-chain.
import { createHash } from "crypto";

function anchorDiscriminator(name: string): number[] {
  const hash = createHash("sha256").update(`global:${name}`).digest();
  return Array.from(hash.subarray(0, 8));
}

// Pre-compute discriminators for mock_lulo (and real Lulo if using same names)
const DEPOSIT_DISCRIMINATOR = anchorDiscriminator("deposit");
const WITHDRAW_DISCRIMINATOR = anchorDiscriminator("withdraw");

// =============================================================================
// LENDING PROTOCOL IMPLEMENTATION
// =============================================================================

// Single implementation that works for both devnet (mock_lulo) and mainnet (real Lulo).
// The target program ID and treasury account are configured via environment variables.
export class OnChainLuloProtocol implements LuloProtocol {
  private program: Program<MyProject>;       // Erebor vault program instance
  private connection: Connection;
  private config: AgentConfig;
  private vaultPda: PublicKey;               // vault state PDA (signs CPIs)
  private strategyPda: PublicKey;            // this agent's strategy PDA
  private strategyTokenPda: PublicKey;       // strategy's token account PDA
  private luloProgramId: PublicKey;          // target protocol (mock_lulo or real Lulo)
  private treasuryPda: PublicKey;            // protocol's treasury token account
  private tokenMint: PublicKey;              // the underlying token mint (e.g., USDC)
  private vaultProgramId: PublicKey;         // Erebor vault program ID (for PDA derivation)

  constructor(
    program: Program<MyProject>,
    connection: Connection,
    config: AgentConfig,
    vaultPda: PublicKey,
    strategyPda: PublicKey,
    strategyTokenPda: PublicKey,
    luloProgramId: PublicKey,
    treasuryPda: PublicKey,
    tokenMint: PublicKey,
    vaultProgramId: PublicKey,
  ) {
    this.program = program;
    this.connection = connection;
    this.config = config;
    this.vaultPda = vaultPda;
    this.strategyPda = strategyPda;
    this.strategyTokenPda = strategyTokenPda;
    this.luloProgramId = luloProgramId;
    this.vaultProgramId = vaultProgramId;
    this.treasuryPda = treasuryPda;
    this.tokenMint = tokenMint;
  }

  // Returns the current observed yield as { rate, hasAccrued }.
  // Reads the on-chain ProtocolPosition to get deposited principal, then
  // compares with the treasury balance to detect accrued yield.
  async getCurrentYield(): Promise<{ rate: number; hasAccrued: boolean }> {
    const positionPda = deriveProtocolPositionPda(this.strategyTokenPda, this.luloProgramId);
    const principal = await fetchProtocolPosition(this.connection, positionPda);
    if (principal <= 0) return { rate: 0, hasAccrued: false };

    const treasuryBalance = await fetchTokenBalance(this.connection, this.treasuryPda).catch(() => 0);
    const surplus = treasuryBalance - principal;
    if (surplus > 0) {
      return { rate: surplus / principal, hasAccrued: true };
    }
    return { rate: 0, hasAccrued: false };
  }

  // Returns this strategy's deposited amount from the on-chain ProtocolPosition.
  // This is the principal tracked by the protocol — the vault reads the same
  // account during report_yield to compute total strategy value.
  async getLentBalance(): Promise<number> {
    const positionPda = deriveProtocolPositionPda(this.strategyTokenPda, this.luloProgramId);
    return fetchProtocolPosition(this.connection, positionPda);
  }

  // Executes a LEND or WITHDRAW action by calling execute_strategy_action
  // on the Erebor vault program. The vault validates the whitelist, then CPIs
  // into the target protocol (mock_lulo or real Lulo).
  async execute(decision: AgentDecision): Promise<string> {
    if (decision.action === "HOLD") return "no-op";

    const isDeposit = decision.action === "LEND";
    const discriminator = isDeposit ? DEPOSIT_DISCRIMINATOR : WITHDRAW_DISCRIMINATOR;

    // Find the AllowedAction PDA that matches this discriminator.
    // The admin must have called add_allowed_action with this discriminator
    // before the agent can execute.
    const strategy = await this.program.account.strategyAllocation.fetch(
      this.strategyPda
    );
    const found = await findAllowedActionByDiscriminator(
      this.program,
      this.strategyPda,
      (strategy as any).actionCount,
      this.luloProgramId,
      discriminator,
      this.vaultProgramId
    );

    if (!found) {
      throw new Error(
        `No active AllowedAction found for ${decision.action} on program ${this.luloProgramId.toBase58()}`
      );
    }

    // Build instruction data: [8-byte discriminator | 8-byte amount as u64 LE]
    // The first 8 bytes must match what's stored in the AllowedAction PDA.
    const instructionData = Buffer.alloc(16);
    Buffer.from(discriminator).copy(instructionData, 0);
    new BN(decision.amount).toArrayLike(Buffer, "le", 8).copy(instructionData, 8);

    // Build remaining_accounts — the accounts the target protocol needs.
    // These match the Deposit/Withdraw account structs in mock_lulo:
    //   strategy_token_account, treasury, mint, vault_authority, token_program, position
    const positionPda = deriveProtocolPositionPda(this.strategyTokenPda, this.luloProgramId);
    const remainingAccounts = [
      { pubkey: this.strategyTokenPda, isSigner: false, isWritable: true },
      { pubkey: this.treasuryPda, isSigner: false, isWritable: true },
      { pubkey: this.tokenMint, isSigner: false, isWritable: false },
      { pubkey: this.vaultPda, isSigner: false, isWritable: false }, // vault_authority
      { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: positionPda, isSigner: false, isWritable: true }, // position tracker
    ];

    // Call execute_strategy_action with retry logic for transient errors.
    const sig = await executeWithRetry(
      () =>
        this.program.methods
          .executeStrategyAction(Buffer.from(instructionData))
          .accountsStrict({
            caller: this.config.agentKeypair.publicKey,
            vaultState: this.vaultPda,
            strategy: this.strategyPda,
            allowedAction: found.pda,
            targetProgram: this.luloProgramId,
          })
          .remainingAccounts(remainingAccounts)
          .signers([this.config.agentKeypair])
          .rpc(),
      this.config.maxRetries,
      this.config.retryDelayMs
    );

    // Principal tracking is now on-chain in the ProtocolPosition account —
    // mock_lulo's deposit/withdraw instructions update it automatically.

    console.log(
      `  [PROTOCOL] ${decision.action} ${(decision.amount / 1e6).toFixed(2)} USDC — tx: ${sig}`
    );
    return sig;
  }
}

// =============================================================================
// RETRY UTILITY
// =============================================================================

async function executeWithRetry(
  fn: () => Promise<string>,
  maxRetries: number,
  delayMs: number
): Promise<string> {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      if (!isTransientError(error) || attempt === maxRetries) throw error;
      console.warn(
        `  Attempt ${attempt} failed, retrying in ${delayMs * attempt}ms...`
      );
      await sleep(delayMs * attempt);
    }
  }
  throw new Error("Unreachable");
}

// Only retry transient network/RPC errors, not program logic errors.
function isTransientError(error: unknown): boolean {
  const msg = String(error);
  return (
    msg.includes("blockhash") ||
    msg.includes("timeout") ||
    msg.includes("429") ||
    msg.includes("503") ||
    msg.includes("ECONNRESET")
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}
